name: se-workshop pipe

on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
#        node-version: [10.x, 8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: |
          yarn install
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          test-command: "cd backend ; cd domain ; yarn test"
      - name: Install API
        run: |
          cd se-workshop-20-interfaces
          npm install
          cd ..
      - name: Install Domain
        run: |
          cd backend
          cd domain
          npm install
          cd ..
          cd ..
      - name: Install Service
        run: |
          cd backend
          cd service
          npm install
          cd ..
          cd ..
      - name: Install AT
        run: |
          cd AT
          npm install
          cd ..
      - name: Compile API
        run: |
          cd se-workshop-20-interfaces
          npm run comp
          cd ..
      - name: Compile Domain
        run: |
          cd backend
          cd domain
          npm run comp
          cd ..
          cd ..
      - name: Compile Service
        run: |
          cd backend
          cd service
          npm run comp
          cd ..
          cd ..
      - name: Compile AT
        run: |
          cd AT
          npm run comp
          cd ..
      - name: Unit Tests
        run: |
          cd backend
          cd domain
          npm run test:cov
          cd ..
          cd ..
      - name: Integration Tests
        run: |
          cd backend
          cd service
          npm test
          cd ..
          cd ..
#      - name: Acceptance Tests
#        run: |
#          cd AT
#          npm test
#          cd ..

