name: se-workshop pipe

on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
#        node-version: [10.x, 8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          cd se-workshop-20-interfaces
          npm install
          cd ..
          cd backend
          cd domain
          npm install
          cd ..
          cd service
          npm install
          cd ..
          cd ..
          cd AT
          npm install
          cd ..
      - name: Compile
        run: |
          cd se-workshop-20-interfaces
          npm run compe
          cd ..
          cd backend
          cd domain
          npm run compe
          cd ..
          cd service
          npm run compe
          cd ..
          cd ..
          cd AT
          npm run compe
          cd ..
      - name: Unit Tests
        run: |
          cd backend
          cd domain
          npm TEST_MODE=1 SILENT=1 jest
          cd ..
          cd ..
      - name: Integration Tests
        run: |
          cd backend
          cd service
          npm TEST_MODE=1 SILENT=1 jest
          cd ..
          cd ..
      - name: Acceptance Tests
        run: |
          cd AT
          npm TEST_MODE=1 SILENT=1 jest
          cd ..
